### ISSUE TITLE
Handle leaks

### ISSUE THREAD

**Issue by RIS2000** [irzyxa/Volume2#112]
**Describe the bug**
After some time handles counter goes up quickly. Maybe devices reinit after out of hibernation.

**Screenshots**
Can provide video if needed.

**Desktop (please complete the following information):**
 - Windows version: 10(1903)
 - Volume² version: 1.1.6.411

**Additional context**
Leaks when changing volume with scroll wheel under notification area with change-sound played.

**Comment by irzyxa** [comment]
Yes, please provide the video.

**Comment by RIS2000** [comment]
> 
> 
> Yes, please provide the video.

https://ufile.io/sm489chy

**Comment by irzyxa** [comment]
I think this happens when you open tray menu. I found leak and will fix it in the next version.

**Comment by irzyxa** [comment]
Fixed version 1.1.7.432

**Comment by RIS2000** [comment]
still the same (
![изображение](https://user-images.githubusercontent.com/30177105/113586871-bd1b1080-9636-11eb-9096-ef55b216d7cd.png)

**Comment by irzyxa** [comment]
What version do you use?

**Comment by RIS2000** [comment]
> 
> 
> What version do you use?

![изображение](https://user-images.githubusercontent.com/30177105/113587746-e7210280-9637-11eb-889d-ebf56dd8ed51.png)

**Comment by irzyxa** [comment]
Can you attach your config.ini?

**Comment by RIS2000** [comment]
> 
> 
> Can you attach your config.ini?


[Volume2 Config.zip](https://github.com/irzyxa/Volume2/files/6258783/Volume2.Config.zip)
