### ISSUE TITLE
Improve dark mode

### ISSUE THREAD

**Issue by irzyxa** [irzyxa/Volume2#170]
Not all elements have changed font color. 
![image](https://user-images.githubusercontent.com/5119360/148834565-130cb517-90ad-4203-812f-64d47c9402bc.png)

**Comment by stasink** [comment]
Ещё бы цвет шрифта регулировать

**Comment by irzyxa** [comment]
@stasink пока что добавил автоматическое опредделение цвета шрифта (белый\черный) в зависимости от фона

**Comment by irzyxa** [comment]
Fixed font color for checkboxes and radiobuttons.
Added automatic font color detection depending on background color
![image](https://user-images.githubusercontent.com/5119360/149631881-2d13700a-1076-4a52-9b10-67dbf74aea2a.png)
![image](https://user-images.githubusercontent.com/5119360/149631926-df3dc8e8-e251-493d-bee8-9eb066b14853.png)

**Comment by irzyxa** [comment]
Interface icons color are changed automatically.
![image](https://user-images.githubusercontent.com/5119360/150691970-4b1b95f7-5f15-4e3e-8eca-0689df84db92.png)

**Comment by J0n1k4** [comment]
Hi,
I still have the problem with font color in dark mode. In last, 447 version.
I have attached just a few screenshots, but the problem is in all settings tabs. If needed - I can attach them all...
Cheers

![2022-03-28_09](https://user-images.githubusercontent.com/26709833/160387270-6dde7d94-ffcf-4831-9db0-4e50b99587b3.png)
![2022-03-28_08](https://user-images.githubusercontent.com/26709833/160387278-6f35ffd9-2e11-446c-8b24-76ff8705b4f5.png)
![2022-03-28_07- Vol2 Dark Screen Edge Probl](https://user-images.githubusercontent.com/26709833/160387280-09f979f4-9c57-4e48-8e4e-4ee07ce9e80f.png)

**Comment by irzyxa** [comment]
@J0n1k4 the latest version can be downloaded from here: https://irzyxa.blogspot.com/p/downloads.html
And all changes have been added to the latest beta version.

**Comment by pigsflew** [comment]
It'd be really nice if there were a windows 10/11 "flat" UI that just used windows colors, along with being able to override RGBA colors for FG/BG/Dim/Accent and disable all the glow and shadows.

**Comment by shodanx2** [comment]
From an aesthetic standpoint I would suggest replacing the "glow" to a "darkening"
I think this would accomplish the flair of the light version but in dark mode
